import { Document } from "mongoose";

export interface IWaterTankCleaning extends document {
  id: string,
  equipment: string,
  classification: string,
  machineryCode: string,
  oldMachineryCode: string,
  plate:string,
  machineType: string,
  brand: string,
  modelMachine: string,
  yearOfManufacture: string,
  hourValue: string,
  inCharge: string,
  stateIdentification: boolean,
  observation: string,
  litersCapacity: string,
  wetLitersPerHour: number,
  pressure: number,
  resolutions: number,
  change: number,
  kmByHour: number,
  cleaningRecord: boolean,
  washWaterTemperatureRecord: boolean,
  maintenance: boolean,
  equipmentTemperatureRecord: boolean,
  costClassification: string,
  costSubClassification: string,
  billOrBuyingGuide: string,
  dateBuy: string,
  supplier: string,
  purchaseObservation: string,
  gpsCode: string,
  gpsSupplier: string,
  loansProperty: string,
  dateLoan: string,
  ioanObservation: string,
  image: string, 
  state: boolean
}
