import { document } from './document';

export interface IWorkerList extends document {
  workerNationality: string,
  rutDniNationality: string,
  identificationDocumentType: string,
  rut: string,
  internalCod: string,
  names: string,
  lastName: string,
  secondLastName: string,
  birthDate: string,
  sex: string,
  civilState: string,
  address: string,
  city: string,
  region: string,
  country: string,
  phone: string,
  email: string,
  recordType: string,
  workerListId: string,
  property: string,

  administrative: boolean,
  dispenser: boolean,
  dispenserResponsible: boolean,
  dispenserChecker: string,
  certificationNumber: string,
  applicator: string,
  applicatorResponsible: boolean,
  applicatorChecker: boolean,
  institution: string,
  expirationDate: string,

  classify: string,
  contractType: string,
  contractDocument: string,
  contractAnnexed: string,
  baseSalary: number,
  calculationType: string,
  startDate: string,
  endDate: string,
  contractFunction: string,
  workerListState: string,
  stateCDate: string,
  stateCUser: string,
  observation: string,

  controlClockAttendance: string,
  assignsAttendanceClassify: string,
  operativeAreaAttendance: string,
  laborWorkAttendance: string,
  hitchContractorDepend: string,
  laborUpdate: boolean,
  laborUpdateDateSince: string,
  laborUpdateDateTill: string,

  rankDay: string,
  priceDayExtraHour:  string,

  youngWorkerBonus: boolean,
  provisionalRegime: boolean,
  workType: string,

  provision: string,
  quote: string,
  savingVoluntary: string,
  sis: string,
  sn: string,
  valueQuote: string,
  valueVolumeSaving: number,
  valueSis: number,
  valueSn: number,

  socialSecurity: string,
  health: string,
  additional: string,
  firstValue: string,
  secondValue: string,
  ccaf: string,
  funNumberOptional: string,
  funNumber: string,
  valueHealth: number,
  valueAdditional: number,
  thirdValue: string,
  fourthValue: string,

  paymentType: string,
  bank: string,
  workerEmail: string,
  accountNumber: number,
  accountType: string,

  particularInstitution: string,
  particularContractNumber: string,
  particularPaymentMethod: string,
  savingTo: string,
  quoteAmount: number,

  collectiveInstitution: string,
  collectiveContractNumber: string,
  collectivePaymentMethod: string,
  savingWorker: string,
  workerAmount: string,
  inputCompany: string,
  amountInputCompany: number,
  state: boolean,
}
