import {Document} from "mongoose";

export interface IWorkersWithPendingData extends document {
  nationality: string,
  rutDniNationality: string,
  identificationDocType: string,
  rut: string,
  internalCod: string,
  names: string,
  lastName: string,
  secondLastName: string,
  birthDay: string,
  sex: string,
  civilState: string,
  address: string,
  city: string,
  region: string,
  country: string,
  phone: string,
  email: string,
  recordType: string,
  identificationId: string,
  property: string,

  functionData: Array<string>,
  certificationNumber: string,
  bpaInstitution: string,
  expirationDate: string,

  classify: string,
  contractType: string,
  contractDocument: string,
  contractAnnexed: string,
  baseSalary: number,
  calculationType: string,
  startDate: string,
  endDate: string,
  contractFunction: string,
  workersWhitPendingDataState: string,
  stateCDate: string,
  stateCUser: string,
  observation: string,

  attendanceClockControl: string,
  attendanceAssignsClass: number,
  attendanceOperativeArea: number,
  attendanceLaborWork: number,
  dependOfContractorHitch: string,
  laborUpdate: boolean,

  dayRange: string,
  priceDayExtraDay: string,

  youngWorkerBonus: boolean,
  provisionalRegime: boolean,
  workerType: string,

  forecast: string,
  quote: string,
  volumeSaving: string,
  sis: string,
  sN: string,
  valueQuote: number,
  valueVolumeSaving: number
  valueSis: number,
  valueSN: number,

  socialSecurity: string,
  health: string,
  additional: string,
  firstValue: string,
  secondValue: string,
  ccaf: string,
  funNumber: string,
  valueHealth: number,
  valueAdditional: number,
  thirdValue: number,
  fourthValue: number,

  paymentMethod: string,
  bank: string,
  accountNumber: string,
  accountType: string,

  particularInstitution: string,
  particularContractNumber: string,
  particularPaymentMethod: string,
  savingTo: string,
  quoteAmount: number,

  collectiveInstitution: string,
  collectiveContractNumber: string,
  collectivePaymentMethod: string,
  workerSavingTo: string,
  workerAmount: number,
  companyContribution: string,
  companyAmount: number,

  firstImageUrlDni: string,
  secondImageUrlDni: string,

  state: boolean,
}
